desc "Fill the database tables with some sample data"
task sample_data: :environment do
  require "faker"
  require "http"
  require "uri"
  require "open-uri"

  if Rails.env.development?
    puts "Deleting existing records..."
    Event.destroy_all
    VenueFollow.delete_all
    VenueRequest.destroy_all
    Venue.destroy_all
    ArtistFollow.delete_all
    Artist.destroy_all
    User.destroy_all
    Owner.destroy_all
  end

  #safety switch for geocoding
  Venue.skip_callback(:save, :before, :geocode_address)

  #owners
  owners = []
  5.times do
    name = Faker::Name.first_name
    owners << Owner.create!(
      firstname: name,
      email: "#{name.downcase}_owner@example.com",
      password: "Password1",
    )
  end

  #users
  5.times do
    name = Faker::Name.first_name
    User.create!(
      email: "#{name.downcase}_user@example.com",
      password: "Password1",
      username: "#{name.downcase}_fan",
    )
  end

  allowed_categories = ["Guitar", "Band", "DJ", "Piano"]
  allowed_genres = ["Rock", "Country", "90s", "Alternative"]
  bios = [
    "Acoustic guitarist playing heartfelt covers from artists like John Mayer and The Lumineers. Always down for a crowd singalong.",
    "Indie-folk duo blending originals and soulful renditions of classic hits. Known for chill patio vibes and tight harmonies.",
    "High-energy cover band playing everything from '90s alt rock to early 2000s pop-punk. Bring your voice — we'll bring the volume.",
    "Vinyl-loving DJ spinning funky house, retro pop, and deep cuts that keep the crowd moving all night.",
    "Piano bar regular mixing Broadway favorites with classic rock singalongs. Requests welcome!",
    "Country guitarist with a modern edge. Think Morgan Wallen meets Eric Church — plus a few surprises.",
    "Loop pedal wizard layering vocals, guitar, and rhythm live. Covers, mashups, and a bit of improv.",
    "Brooklyn-based 3-piece band playing nostalgic '90s covers and alternative deep cuts. Intimate shows, loud memories.",
    "Soulful solo artist bringing smooth vocals and acoustic takes on R&B classics. Ideal for date nights and dim lighting.",
    "DJ specializing in dancefloor-filling mashups, throwbacks, and late-night energy sets. No skips.",
  ]
  # artists
  artists = []
  5.times do
    name = Faker::Name.first_name

    artist = Artist.create!(
      firstname: name,
      email: "#{name.downcase}_artist@example.com",
      password: "Password1",
      username: "#{name.downcase} music",
      genre: allowed_genres.sample,
      category: allowed_categories.sample,
      website: "https://example.com",
      bio: bios.sample,
      instagram_url: "https://www.google.com",
      tiktok_url: "https://www.google.com",
      youtube_url: "https://www.google.com",
      spotify_url: "https://www.google.com",
    )

    #avatar_url = Faker::Avatar.image(slug: name.downcase, size: "300x300", format: "png")
    avatar_url = "https://i.pravatar.cc/300?u=#{SecureRandom.uuid}"

    artist.image.attach(
      io: URI.open(avatar_url),
      filename: "#{name.downcase}.png",
      content_type: "image/png",
    )

    artists << artist
  end

  #VENUES WITH NO GOOGLEMAPS API
  venues = []

  manual_venues = [
    # Original Chicago venues
    {
      name: "The Green Mill",
      street_address: "4802 N Broadway",
      city: "Chicago",
      state: "IL",
      zip_code: "60640",
      category: "Music Hall",
      website: "https://greenmilljazz.com",
      latitude: 41.9701,
      longitude: -87.6598,
    },
    {
      name: "Schubas Tavern",
      street_address: "3159 N Southport Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60657",
      category: "Club",
      website: "https://lh-st.com/venues/schubas-tavern",
      latitude: 41.9409,
      longitude: -87.6636,
    },
    {
      name: "Constellation",
      street_address: "3111 N Western Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60618",
      category: "Bar",
      website: "https://constellation-chicago.com",
      latitude: 41.9383,
      longitude: -87.6889,
    },
    {
      name: "Reggies Rock Club",
      street_address: "2109 S State St",
      city: "Chicago",
      state: "IL",
      zip_code: "60616",
      category: "Music Hall",
      website: "https://reggieslive.com",
      latitude: 41.8539,
      longitude: -87.6272,
    },
    {
      name: "Hideout Inn",
      street_address: "1354 W Wabansia Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60642",
      category: "Club",
      website: "https://hideoutchicago.com",
      latitude: 41.9132,
      longitude: -87.6622,
    },
    {
      name: "Lincoln Hall",
      street_address: "2424 N Lincoln Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60614",
      category: "Bar",
      website: "https://lh-st.com/venues/lincoln-hall",
      latitude: 41.9260,
      longitude: -87.6495,
    },
    {
      name: "Subterranean",
      street_address: "2011 W North Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60647",
      category: "Music Hall",
      website: "https://subt.net",
      latitude: 41.9106,
      longitude: -87.6775,
    },
    {
      name: "Beat Kitchen",
      street_address: "2100 W Belmont Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60618",
      category: "Club",
      website: "https://beatkitchen.com",
      latitude: 41.9393,
      longitude: -87.6805,
    },
    {
      name: "Sleeping Village",
      street_address: "3734 W Belmont Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60618",
      category: "Bar",
      website: "https://sleeping-village.com",
      latitude: 41.9399,
      longitude: -87.7202,
    },
    {
      name: "Thalia Hall",
      street_address: "1807 S Allport St",
      city: "Chicago",
      state: "IL",
      zip_code: "60608",
      category: "Music Hall",
      website: "https://thaliahallchicago.com",
      latitude: 41.8577,
      longitude: -87.6555,
    },
    # Google Places Chicago venues
    {
      name: "State and Lake Chicago Tavern",
      street_address: "201 N State St Floor 1",
      city: "Chicago",
      state: "IL",
      zip_code: "60601",
      category: "Bar",
      website: "https://stateandlakechicago.com/?y_source=1_MTU0MDUzNDItNzE1LWxvY2F0aW9uLndlYnNpdGU%3D",
      latitude: 41.8860414,
      longitude: -87.62762330000001,
    },
    {
      name: "Copper Fox Gastropub",
      street_address: "155 E Ontario St",
      city: "Chicago",
      state: "IL",
      zip_code: "60611",
      category: "Bar",
      website: "https://www.copperfoxchicago.com/?utm_source=google&utm_medium=organic&utm_campaign=business_listing",
      latitude: 41.8931149,
      longitude: -87.6229269,
    },
    {
      name: "Elephant & Castle",
      street_address: "111 W Adams St",
      city: "Chicago",
      state: "IL",
      zip_code: "60603",
      category: "Bar",
      website: "https://www.elephantcastle.com/en/locations/il/chicago/111-west-adams-street",
      latitude: 41.8793112,
      longitude: -87.6314087,
    },
    {
      name: "The Dearborn",
      street_address: "145 N Dearborn St",
      city: "Chicago",
      state: "IL",
      zip_code: "60602",
      category: "Bar",
      website: "http://www.thedearborntavern.com/",
      latitude: 41.8843373,
      longitude: -87.6292766,
    },
    {
      name: "Lockwood Restaurant & Bar",
      street_address: "17 E Monroe St",
      city: "Chicago",
      state: "IL",
      zip_code: "60603",
      category: "Bar",
      website: "http://www.lockwoodrestaurant.com/",
      latitude: 41.88028200000001,
      longitude: -87.62706,
    },
    {
      name: "Farm Bar Lakeview",
      street_address: "1300 W Wellington Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60657",
      category: "Bar",
      website: "https://www.farm-bar.com/",
      latitude: 41.9363515,
      longitude: -87.6614204,
    },
    {
      name: "Armitage Alehouse",
      street_address: "1000 W Armitage Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60614",
      category: "Bar",
      website: "https://armitagealehouse.com/",
      latitude: 41.91835319999999,
      longitude: -87.6536,
    },
    {
      name: "Butch McGuire's",
      street_address: "20 W Division St",
      city: "Chicago",
      state: "IL",
      zip_code: "60610",
      category: "Bar",
      website: "https://butchmcguires.com/",
      latitude: 41.9040574,
      longitude: -87.6296357,
    },
    {
      name: "The Galway Arms",
      street_address: "2442 N Clark St",
      city: "Chicago",
      state: "IL",
      zip_code: "60614",
      category: "Bar",
      website: "http://www.galwayarms.com/",
      latitude: 41.9266257,
      longitude: -87.6413218,
    },
    {
      name: "The Red Lion Pub",
      street_address: "2446 N Lincoln Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60614",
      category: "Bar",
      website: "http://redlionchicago.com/",
      latitude: 41.9262933,
      longitude: -87.65043460000001,
    },
    {
      name: "The Perch Kitchen and Tap",
      street_address: "1932 W Division St",
      city: "Chicago",
      state: "IL",
      zip_code: "60622",
      category: "Bar",
      website: "http://www.perchchicago.com/",
      latitude: 41.903357,
      longitude: -87.6762365,
    },
    {
      name: "Lone Owl",
      street_address: "1547 N Milwaukee Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60622",
      category: "Bar",
      website: "http://loneowlpub.com/",
      latitude: 41.90975650000001,
      longitude: -87.67605189999999,
    },
    {
      name: "The Hurley Tap",
      street_address: "1645 W Cortland St",
      city: "Chicago",
      state: "IL",
      zip_code: "60622",
      category: "Bar",
      website: "http://www.hurleytap.com/",
      latitude: 41.9158313,
      longitude: -87.6695797,
    },
    {
      name: "The Wolfhound Bar and Kitchen",
      street_address: "3188 N Elston Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60618",
      category: "Bar",
      website: "http://wolfhoundchicago.com/",
      latitude: 41.9390744,
      longitude: -87.6982328,
    },
    {
      name: "Cleos Bar and Grill",
      street_address: "1935 W Chicago Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60622",
      category: "Bar",
      website: "http://www.cleospub.com/",
      latitude: 41.8958056,
      longitude: -87.676,
    },
    {
      name: "Long Room Chicago",
      street_address: "1612 W Irving Park Rd Ste 1",
      city: "Chicago",
      state: "IL",
      zip_code: "60613",
      category: "Bar",
      website: "http://www.longroomchicago.com/",
      latitude: 41.9544231,
      longitude: -87.6696958,
    },
    {
      name: "The Globe Pub",
      street_address: "1934 W Irving Park Rd",
      city: "Chicago",
      state: "IL",
      zip_code: "60613",
      category: "Bar",
      website: "http://theglobepub.com/",
      latitude: 41.9543896,
      longitude: -87.67774639999999,
    },
    {
      name: "The Green Door Tavern",
      street_address: "678 N Orleans St",
      city: "Chicago",
      state: "IL",
      zip_code: "60654",
      category: "Bar",
      website: "https://www.greendoorchicago.com/",
      latitude: 41.89462820000001,
      longitude: -87.6374062,
    },
    {
      name: "Bar Louie - Printers Row",
      street_address: "47 W Polk St",
      city: "Chicago",
      state: "IL",
      zip_code: "60605",
      category: "Bar",
      website: "https://www.barlouie.com/locations/us/il/chicago/printers-row?utm_source=other&utm_medium=listings",
      latitude: 41.8720742,
      longitude: -87.62890469999999,
    },
    {
      name: "Miller's Pub",
      street_address: "134 S Wabash Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60603",
      category: "Bar",
      website: "http://www.millerspub.com/",
      latitude: 41.8798217,
      longitude: -87.62634829999999,
    },
    {
      name: "Franklin Tap",
      street_address: "325 S Franklin St",
      city: "Chicago",
      state: "IL",
      zip_code: "60606",
      category: "Bar",
      website: "https://www.franklintap.com/",
      latitude: 41.8773351,
      longitude: -87.63495549999999,
    },
    {
      name: "Timothy O'Toole's Pub Chicago",
      street_address: "622 N Fairbanks Ct",
      city: "Chicago",
      state: "IL",
      zip_code: "60611",
      category: "Bar",
      website: "http://www.timothyotooles.com/chicago/",
      latitude: 41.89325210000001,
      longitude: -87.6204905,
    },
    {
      name: "Bungalow by Middle Brow",
      street_address: "2840 W Armitage Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60647",
      category: "Bar",
      website: "http://www.middlebrowbeer.com/",
      latitude: 41.9177853,
      longitude: -87.6988914,
    },
    {
      name: "Bitter Pops",
      street_address: "3357 N Lincoln Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60657",
      category: "Bar",
      website: "https://bitterpops.com/",
      latitude: 41.94315450000001,
      longitude: -87.6708106,
    },
    {
      name: "Cafe Robey",
      street_address: "1600 N Milwaukee Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60647",
      category: "Bar",
      website: "https://www.caferobey.com/",
      latitude: 41.9106629,
      longitude: -87.67812339999999,
    },
    {
      name: "Joe's on Weed St.",
      street_address: "940 W Weed St",
      city: "Chicago",
      state: "IL",
      zip_code: "60642",
      category: "Bar",
      website: "http://www.joesbar.com/",
      latitude: 41.9099108,
      longitude: -87.6521578,
    },
    {
      name: "Piece Pizzeria and Brewery",
      street_address: "1927 W North Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60622",
      category: "Bar",
      website: "http://www.piecechicago.com/",
      latitude: 41.9103042,
      longitude: -87.6761289,
    },
    {
      name: "Billy Goat Tavern (Wrigleyville)",
      street_address: "3724 N Clark St",
      city: "Chicago",
      state: "IL",
      zip_code: "60613",
      category: "Bar",
      website: "https://www.billygoattavern.com/",
      latitude: 41.9496794,
      longitude: -87.6587632,
    },
    {
      name: "The Pony Inn",
      street_address: "1638 W Belmont Ave",
      city: "Chicago",
      state: "IL",
      zip_code: "60657",
      category: "Bar",
      website: "http://www.theponychicago.com/",
      latitude: 41.93984459999999,
      longitude: -87.6701971,
    },
    # Virginia Beach venues
    {
      name: "Chick's Oyster Bar",
      street_address: "2143 Vista Cir",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23451",
      category: "Bar",
      website: "https://www.chicksoysterbar.com",
      latitude: 36.9051014305217, 
      longitude: -76.08533268196011,
    },
    {
      name: "The Back Deck",
      street_address: "3323 Shore Dr",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23451",
      category: "Bar",
      website: "https://thebackdeckvb.com",
      latitude: 36.906561701248606, 
      longitude: -76.08728013696928,
    },
    {
      name: "Commonwealth Brewing Company",
      street_address: "2444 Pleasure House Rd",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23455",
      category: "Bar",
      website: "https://commonwealthbrewingcompany.com",
      latitude: 36.91339629963791, 
      longitude: -76.13186828993565,
    },
    {
      name: "HK on the Bay",
      street_address: "4600 Lookout Rd",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23455",
      category: "Bar",
      website: "https://www.hkonthebay.com",
      latitude: 36.915746433951796, 
      longitude: -76.12759873660148,
    },
    {
      name: "Buoy 44",
      street_address: "4536 Ocean View Ave",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23455",
      category: "Bar",
      website: "https://www.buoy44vb.com",
      latitude: 36.91739870885306, 
      longitude: -76.12660951887025,
    },
    {
      name: "Jose Tequila",
      street_address: "3629 Shore Dr",
      city: "Virginia Beach",
      state: "VA",
      zip_code: "23451",
      category: "Bar",
      website: "https://jose-tequilas.com",
      latitude: 36.907715284133495, 
      longitude: -76.0981830614175,
    },
    # Long Island venues
    {
      name: "Country Corner",
      street_address: "270 Main St",
      city: "Setauket- East Setauket",
      state: "NY",
      zip_code: "11733",
      category: "Bar",
      website: "http://www.countrycornerli.com/",
      latitude: 40.9430556,
      longitude: -73.1022222,
    },
    {
      name: "Port Bistro and Pub",
      street_address: "201 Main St",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "http://portbistroandpub.com/",
      latitude: 40.94585439999999,
      longitude: -73.06830430000001,
    },
    {
      name: "Billie's 1890 Saloon",
      street_address: "304 Main St",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "http://www.billies1890.com/",
      latitude: 40.9450332,
      longitude: -73.0680829,
    },
    {
      name: "The Whiskey Barrel",
      street_address: "138 Main St",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "http://www.thewhiskeybarrelpj.com/",
      latitude: 40.9454981,
      longitude: -73.068578,
    },
    {
      name: "Portside Bar & Grill",
      street_address: "242 Traders Cove parking lot",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "https://instagram.com/portsideportjeff?igshid=NTc4MTIwNjQ2YQ==",
      latitude: 40.94548109999999,
      longitude: -73.067663,
    },
    {
      name: "Tara Inn",
      street_address: "1519 Main St",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "https://www.facebook.com/tara.inn.7/?paipv=0&eav=AfZbESRTdHR49PovPNQTQNlQ8GQbml9H4dTkLg6DN-ffCj4XLRtnbLRUZWxfr8DFDLc&_rdr",
      latitude: 40.9357163,
      longitude: -73.0555124,
    },
    {
      name: "Grumpy Jack's",
      street_address: "28 Oakland Ave",
      city: "Port Jefferson",
      state: "NY",
      zip_code: "11777",
      category: "Bar",
      website: "https://www.grumpyjacksportjeff.com/",
      latitude: 40.9370985,
      longitude: -73.0542392,
    },
    {
      name: "The Edge At Lulu's",
      street_address: "388 Medford Ave",
      city: "Patchogue",
      state: "NY",
      zip_code: "11772",
      category: "Bar",
      website: "",
      latitude: 40.7815124,
      longitude: -73.0088231,
    },
    {
      name: "Reese's 1900",
      street_address: "70 N Ocean Ave",
      city: "Patchogue",
      state: "NY",
      zip_code: "11772",
      category: "Bar",
      website: "http://www.reeses1900.com/",
      latitude: 40.7670021,
      longitude: -73.0151884,
    },
    {
      name: "Village Idiot Pub",
      street_address: "8 E Main St",
      city: "Patchogue",
      state: "NY",
      zip_code: "11772",
      category: "Bar",
      website: "https://villageidiotpubs.com/villageidiotpatchogue?utm_source=google",
      latitude: 40.7655245,
      longitude: -73.01485799999999,
    },
    {
      name: "Rudi's Bar & Grill",
      street_address: "554 NY-112",
      city: "Patchogue",
      state: "NY",
      zip_code: "11772",
      category: "Bar",
      website: "http://www.rudisbarandgrill.com/",
      latitude: 40.78770349999999,
      longitude: -73.00958179999999,
    },
    {
      name: "Dublin Deck Tiki Bar and Grill",
      street_address: "327 River Ave",
      city: "Patchogue",
      state: "NY",
      zip_code: "11772",
      category: "Bar",
      website: "https://www.dublindeck.com/",
      latitude: 40.75354069999999,
      longitude: -73.0200499,
    },
    {
      name: "The Bench",
      street_address: "1095 NY-25A",
      city: "Stony Brook",
      state: "NY",
      zip_code: "11790",
      category: "Bar",
      website: "http://www.thebenchbar.com/",
      latitude: 40.9203017,
      longitude: -73.129227,
    },
    {
      name: "Sweet Mama's",
      street_address: "121 Main St",
      city: "Stony Brook",
      state: "NY",
      zip_code: "11790",
      category: "Bar",
      website: "https://www.sweetmamasli.com/",
      latitude: 40.917478,
      longitude: -73.1465314,
    },
    {
      name: "Schnitzels",
      street_address: "77 Main St",
      city: "Stony Brook",
      state: "NY",
      zip_code: "11790",
      category: "Bar",
      website: "http://eat-schnitzels.com/",
      latitude: 40.916231,
      longitude: -73.1462779,
    },
    {
      name: "Mirabelle Tavern",
      street_address: "150 Main St",
      city: "Stony Brook",
      state: "NY",
      zip_code: "11790",
      category: "Bar",
      website: "https://www.mirabelleatthreevillageinn.com/",
      latitude: 40.919212,
      longitude: -73.14828399999999,
    },
    {
      name: "Bliss",
      street_address: "766 NY-25A",
      city: "Setauket- East Setauket",
      state: "NY",
      zip_code: "11733",
      category: "Bar",
      website: "http://blissli.com/",
      latitude: 40.9267682,
      longitude: -73.1180294,
    },
    {
      name: "Bird on the Roof",
      street_address: "47 S Elmwood Ave",
      city: "Montauk",
      state: "NY",
      zip_code: "11954",
      category: "Bar",
      website: "http://www.birdontheroof.com/",
      latitude: 41.0336271,
      longitude: -71.9442753,
    },
    {
      name: "The Point Bar & Grill",
      street_address: "697 Montauk Hwy",
      city: "Montauk",
      state: "NY",
      zip_code: "11954",
      category: "Bar",
      website: "https://www.pointbarandgrill.com/",
      latitude: 41.0333737,
      longitude: -71.9467698,
    },
    {
      name: "Shagwong",
      street_address: "774 Montauk Hwy",
      city: "Montauk",
      state: "NY",
      zip_code: "11954",
      category: "Bar",
      website: "http://shagwongtavern.com/",
      latitude: 41.03515,
      longitude: -71.9429111,
    },
    {
      name: "The Montauket",
      street_address: "88 Firestone Rd",
      city: "Montauk",
      state: "NY",
      zip_code: "11954",
      category: "Bar",
      website: "https://www.themontauket.com/",
      latitude: 41.0542431,
      longitude: -71.95757379999999,
    },
    {
      name: "The Beach Club at Gurney's Montauk",
      street_address: "290 Old Montauk Hwy",
      city: "Montauk",
      state: "NY",
      zip_code: "11954",
      category: "Bar",
      website: "https://www.gurneysresorts.com/montauk",
      latitude: 41.0155385,
      longitude: -71.9917213,
    },
    {
      name: "East Hampton Grill",
      street_address: "99 N Main St",
      city: "East Hampton",
      state: "NY",
      zip_code: "11937",
      category: "Bar",
      website: "http://www.easthamptongrill.com",
      latitude: 40.96906649999999,
      longitude: -72.1824173,
    },
    {
      name: "Blue Parrot",
      street_address: "33A Main St",
      city: "East Hampton",
      state: "NY",
      zip_code: "11937",
      category: "Bar",
      website: "http://www.blueparroteasthampton.com/",
      latitude: 40.9634765,
      longitude: -72.1859568,
    },
    {
      name: "1770 House Restaurant & Inn",
      street_address: "143 Main St",
      city: "East Hampton",
      state: "NY",
      zip_code: "11937",
      category: "Bar",
      website: "http://www.1770house.com/",
      latitude: 40.95886830000001,
      longitude: -72.19037159999999,
    },
    {
      name: "Little Charli East Hampton",
      street_address: "44 Three Mile Harbor Rd",
      city: "East Hampton",
      state: "NY",
      zip_code: "11937",
      category: "Bar",
      website: "http://www.littlecharli.com/",
      latitude: 40.97566399999999,
      longitude: -72.18164279999999,
    },
    {
      name: "Nick & Toni's",
      street_address: "136 N Main St",
      city: "East Hampton",
      state: "NY",
      zip_code: "11937",
      category: "Bar",
      website: "http://www.nickandtonis.com/",
      latitude: 40.970181,
      longitude: -72.181375,
    },
    {
      name: "flora",
      street_address: "149 Main St",
      city: "Westhampton Beach",
      state: "NY",
      zip_code: "11978",
      category: "Bar",
      website: "http://florawhb.com/",
      latitude: 40.8098799,
      longitude: -72.6414365,
    },
    {
      name: "Boom Burger",
      street_address: "85 Montauk Hwy",
      city: "Westhampton Beach",
      state: "NY",
      zip_code: "11978",
      category: "Bar",
      website: "https://boomburgerwhb.com/",
      latitude: 40.82175529999999,
      longitude: -72.6476662,
    },
    {
      name: "Local Provisions",
      street_address: "121A Main St",
      city: "Westhampton Beach",
      state: "NY",
      zip_code: "11978",
      category: "Bar",
      website: "http://www.localprovisionswhb.com/",
      latitude: 40.8097309,
      longitude: -72.6427918,
    },
    {
      name: "Sydney's Taylor Made Cuisine",
      street_address: "32 Mill Rd A",
      city: "Westhampton Beach",
      state: "NY",
      zip_code: "11978",
      category: "Bar",
      website: "http://www.sydneysgourmet.com/",
      latitude: 40.81107739999999,
      longitude: -72.64156150000001,
    },
    {
      name: "The Ketch",
      street_address: "62 Montauk Hwy",
      city: "Westhampton",
      state: "NY",
      zip_code: "11977",
      category: "Bar",
      website: "https://www.the-ketch.net/",
      latitude: 40.8196611,
      longitude: -72.6670717,
    },
    {
      name: "The 1901 Grill",
      street_address: "26 Sunnyside Ave",
      city: "Shelter Island Heights",
      state: "NY",
      zip_code: "11965",
      category: "Bar",
      website: "https://the1901grill.com/",
      latitude: 41.0775612,
      longitude: -72.3588841,
    },
    {
      name: "Bruce & Son",
      street_address: "208 Main St",
      city: "Greenport",
      state: "NY",
      zip_code: "11944",
      category: "Bar",
      website: "http://bruceandsongreenport.com/",
      latitude: 41.102707,
      longitude: -72.358949,
    },
    {
      name: "Stars Cafe",
      street_address: "17 Grand Ave",
      city: "Shelter Island Heights",
      state: "NY",
      zip_code: "11965",
      category: "Bar",
      website: "https://www.starscafeshelterisland.com/",
      latitude: 41.08345509999999,
      longitude: -72.3549105,
    },
    {
      name: "PORT Waterfront Bar & Grill",
      street_address: "104 3rd St",
      city: "Greenport",
      state: "NY",
      zip_code: "11944",
      category: "Bar",
      website: "https://www.portbarandgrill.com/",
      latitude: 41.10088330000001,
      longitude: -72.3621752,
    },
    {
      name: "First and South Restaurant & Bar",
      street_address: "100 South St",
      city: "Greenport",
      state: "NY",
      zip_code: "11944",
      category: "Bar",
      website: "https://www.firstandsouth.com/",
      latitude: 41.1035584,
      longitude: -72.3611964,
    },
    {
      name: "Good Ground Tavern",
      street_address: "239 E Montauk Hwy",
      city: "Hampton Bays",
      state: "NY",
      zip_code: "11946",
      category: "Bar",
      website: "https://canoeplace.com/dining/",
      latitude: 40.88539269999999,
      longitude: -72.5032319,
    },
    {
      name: "The Bays Bar & Grill",
      street_address: "214 W Montauk Hwy",
      city: "Hampton Bays",
      state: "NY",
      zip_code: "11946",
      category: "Bar",
      website: "",
      latitude: 40.87245009999999,
      longitude: -72.5408312,
    },
    {
      name: "The Station Bar",
      street_address: "22 Shinnecock Rd",
      city: "Hampton Bays",
      state: "NY",
      zip_code: "11946",
      category: "Bar",
      website: "http://www.thestationbarhamptons.com/",
      latitude: 40.8564396,
      longitude: -72.5099056,
    },
    {
      name: "The Pizza Place - Hampton Bays",
      street_address: "125 W Montauk Hwy",
      city: "Hampton Bays",
      state: "NY",
      zip_code: "11946",
      category: "Bar",
      website: "http://www.pizzaplaceinhamptonbays.com/",
      latitude: 40.876372,
      longitude: -72.5290349,
    },
    {
      name: "Sundays On The Bay",
      street_address: "369 Dune Rd",
      city: "Hampton Bays",
      state: "NY",
      zip_code: "11946",
      category: "Bar",
      website: "http://www.sundaysonthebay.com/",
      latitude: 40.8419231,
      longitude: -72.4804712,
    },
    # NYC venues
    {
      name: "Brickyard Craft Kitchen & Bar",
      street_address: "23 Park Pl",
      city: "New York",
      state: "NY",
      zip_code: "10007",
      category: "Bar",
      website: "http://brickyardbarnyc.com/",
      latitude: 40.7133249,
      longitude: -74.008664,
    },
    {
      name: "The Red Lion",
      street_address: "151 Bleecker St",
      city: "New York",
      state: "NY",
      zip_code: "10012",
      category: "Bar",
      website: "http://redlionnyc.com/",
      latitude: 40.7284222,
      longitude: -73.9994518,
    },
    {
      name: "The Dead Rabbit",
      street_address: "30 Water St",
      city: "New York",
      state: "NY",
      zip_code: "10004",
      category: "Bar",
      website: "https://thedeadrabbit.com/?utm_source=google_business_profile&utm_medium=gbp_view_website&utm_campaign=google_business_profile",
      latitude: 40.70326850000001,
      longitude: -74.0110218,
    },
    {
      name: "Loreley Beer Garden",
      street_address: "7 Rivington St",
      city: "New York",
      state: "NY",
      zip_code: "10002",
      category: "Bar",
      website: "https://www.loreleynyc.com/",
      latitude: 40.7212299,
      longitude: -73.99287249999999,
    },
    {
      name: "The Skinny Bar and Lounge",
      street_address: "174 Orchard St",
      city: "New York",
      state: "NY",
      zip_code: "10002",
      category: "Bar",
      website: "http://theskinnynyc.com/",
      latitude: 40.72154099999999,
      longitude: -73.988186,
    },
    {
      name: "O'Donoghue's Times Square",
      street_address: "156 W 44th St",
      city: "New York",
      state: "NY",
      zip_code: "10036",
      category: "Bar",
      website: "http://www.odpubnyc.com/",
      latitude: 40.7569427,
      longitude: -73.9852828,
    },
    {
      name: "The Westbury",
      street_address: "20 W 38th St",
      city: "New York",
      state: "NY",
      zip_code: "10018",
      category: "Bar",
      website: "https://www.thewestburynyc.com/",
      latitude: 40.7512301,
      longitude: -73.9838982,
    },
    {
      name: "Sir Henry's",
      street_address: "795 8th Ave 1st Fl",
      city: "New York",
      state: "NY",
      zip_code: "10019",
      category: "Bar",
      website: "https://sirhenrysnyc.com/",
      latitude: 40.7613102,
      longitude: -73.9871615,
    },
    {
      name: "Sefton",
      street_address: "1373 1st Ave",
      city: "New York",
      state: "NY",
      zip_code: "10021",
      category: "Bar",
      website: "https://www.thesefton.com/",
      latitude: 40.76906589999999,
      longitude: -73.955394,
    },
    {
      name: "Gossip",
      street_address: "733 9th Ave",
      city: "New York",
      state: "NY",
      zip_code: "10019",
      category: "Bar",
      website: "http://www.gossipbarnyc.com/",
      latitude: 40.7633552,
      longitude: -73.989384,
    },
    {
      name: "The Long Acre Tavern",
      street_address: "146 W 47th St",
      city: "New York",
      state: "NY",
      zip_code: "10036",
      category: "Bar",
      website: "http://longacrenyc.com/",
      latitude: 40.7586546,
      longitude: -73.9836163,
    },
    {
      name: "Alfie's Kitchen & Craft Beer Bar",
      street_address: "800 9th Ave",
      city: "New York",
      state: "NY",
      zip_code: "10019",
      category: "Bar",
      website: "http://www.alfiesnyc.com/",
      latitude: 40.7653757,
      longitude: -73.98725309999999,
    },
    {
      name: "All Stars Sports Bar & Grill",
      street_address: "327 W 57th St",
      city: "New York",
      state: "NY",
      zip_code: "10019",
      category: "Bar",
      website: "https://www.allstarsportsbarandgrill.com/",
      latitude: 40.76745560000001,
      longitude: -73.98414509999999,
    },
    {
      name: "Rudy's Bar & Grill",
      street_address: "627 9th Ave",
      city: "New York",
      state: "NY",
      zip_code: "10036",
      category: "Bar",
      website: "http://www.rudysbarnyc.com/",
      latitude: 40.7600309,
      longitude: -73.99179509999999,
    },
    {
      name: "The Three Monkeys",
      street_address: "832 8th Ave",
      city: "New York",
      state: "NY",
      zip_code: "10019",
      category: "Bar",
      website: "http://thethreemonkeysbar.com/",
      latitude: 40.7623663,
      longitude: -73.9857634,
    },
    {
      name: "The Penrose Bar",
      street_address: "1590 2nd Ave",
      city: "New York",
      state: "NY",
      zip_code: "10028",
      category: "Bar",
      website: "http://www.penrosebar.com/",
      latitude: 40.7754985,
      longitude: -73.9532816,
    },
    {
      name: "Pig 'N' Whistle Public House",
      street_address: "58 W 48th St",
      city: "New York",
      state: "NY",
      zip_code: "10036",
      category: "Bar",
      website: "https://www.pignwhistle48st.com/",
      latitude: 40.75808809999999,
      longitude: -73.98055560000002,
    },
    {
      name: "Connolly's",
      street_address: "121 W 45th St",
      city: "New York",
      state: "NY",
      zip_code: "10036",
      category: "Bar",
      website: "https://www.connollyspubandrestaurant.com/",
      latitude: 40.7573681,
      longitude: -73.9835798,
    },
    {
      name: "Hudson Yards Tavern",
      street_address: "360 9th Ave",
      city: "New York",
      state: "NY",
      zip_code: "10001",
      category: "Bar",
      website: "http://hudsonyardstavern.nyc/",
      latitude: 40.75103109999999,
      longitude: -73.9976192,
    },
    {
      name: "Bourbon and Branch",
      street_address: "155 W 33rd St",
      city: "New York",
      state: "NY",
      zip_code: "10001",
      category: "Bar",
      website: "https://bourbonandbranchnyc.com/",
      latitude: 40.75030160000001,
      longitude: -73.9904585,
    },
    {
      name: "District Tap House",
      street_address: "246 W 38th St",
      city: "New York",
      state: "NY",
      zip_code: "10018",
      category: "Bar",
      website: "http://www.districttaphouse.com/",
      latitude: 40.75403929999999,
      longitude: -73.99050129999999,
    },
    {
      name: "Thief",
      street_address: "595 Union Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11211",
      category: "Bar",
      website: "http://www.thiefnyc.com/",
      latitude: 40.71809199999999,
      longitude: -73.95252649999999,
    },
    {
      name: "Brooklyn Public House",
      street_address: "247 DeKalb Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11205",
      category: "Bar",
      website: "http://www.brooklynpublic.com/",
      latitude: 40.6895906,
      longitude: -73.96936459999999,
    },
    {
      name: "Keg & Lantern Greenpoint",
      street_address: "97 Nassau Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11222",
      category: "Bar",
      website: "http://www.kegandlanternbrooklyn.com/",
      latitude: 40.72411079999999,
      longitude: -73.9503312,
    },
    {
      name: "Bantry Bay Publick House",
      street_address: "33-01 Greenpoint Ave",
      city: "Long Island City",
      state: "NY",
      zip_code: "11101",
      category: "Bar",
      website: "http://www.bantrybaynyc.com/",
      latitude: 40.7356919,
      longitude: -73.9347422,
    },
    {
      name: "O'Hanlon's",
      street_address: "349 E 14th St",
      city: "New York",
      state: "NY",
      zip_code: "10003",
      category: "Bar",
      website: "https://instagram.com/ohanlonsbarnyc?utm_source=qr&igshid=MzNlNGNkZWQ4Mg==",
      latitude: 40.7316636,
      longitude: -73.9829316,
    },
    {
      name: "McMahon's Public House",
      street_address: "39 5th Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11217",
      category: "Bar",
      website: "https://www.mcmahonspublic.com/",
      latitude: 40.68165879999999,
      longitude: -73.97650770000001,
    },
    {
      name: "O'Keefe's Bar & Grill",
      street_address: "62 Court St",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11201",
      category: "Bar",
      website: "http://www.okeefesbarandgrill.com/",
      latitude: 40.6921197,
      longitude: -73.9915367,
    },
    {
      name: "Abilene Bar",
      street_address: "442 Court St",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11231",
      category: "Bar",
      website: "http://www.abilenebarbrooklyn.com/",
      latitude: 40.678932,
      longitude: -73.9977005,
    },
    {
      name: "Park Slope Ale House",
      street_address: "356 6th Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11215",
      category: "Bar",
      website: "http://parkslopealehouse.com/",
      latitude: 40.6706291,
      longitude: -73.9820343,
    },
    {
      name: "Corner Bar",
      street_address: "60 Canal St",
      city: "New York",
      state: "NY",
      zip_code: "10002",
      category: "Bar",
      website: "http://cornerbarnyc.com/",
      latitude: 40.7149395,
      longitude: -73.9922971,
    },
    {
      name: "O'Hara's Restaurant and Pub",
      street_address: "120 Cedar St",
      city: "New York",
      state: "NY",
      zip_code: "10006",
      category: "Bar",
      website: "https://oharasrestaurantandpub.site/",
      latitude: 40.7095008,
      longitude: -74.0126642,
    },
    {
      name: "White Horse Tavern - Financial District",
      street_address: "25 Bridge St",
      city: "New York",
      state: "NY",
      zip_code: "10004",
      category: "Bar",
      website: "http://www.whitehorsetavernfidi.com/",
      latitude: 40.703806,
      longitude: -74.012371,
    },
    {
      name: "Wingbar",
      street_address: "275 Smith St",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11231",
      category: "Bar",
      website: "http://www.thewingbar.com/",
      latitude: 40.6824954,
      longitude: -73.99314249999999,
    },
    {
      name: "Brooklyn Burgers & Beer",
      street_address: "259 5th Ave",
      city: "Brooklyn",
      state: "NY",
      zip_code: "11215",
      category: "Bar",
      website: "http://www.brooklynburgersandbeer.com/",
      latitude: 40.67441799999999,
      longitude: -73.981649,
    },
  ]

  # Helper method to check name similarity
  def similar_venue_exists?(venue_name, existing_venues)
    venue_name_clean = venue_name.downcase.gsub(/[^a-z0-9\s]/, "").strip

    existing_venues.any? do |existing|
      existing_name_clean = existing[:name].downcase.gsub(/[^a-z0-9\s]/, "").strip

      # Check for exact match or if one name contains the other (for cases like "The Green Door" vs "Green Door Tavern")
      venue_name_clean == existing_name_clean ||
      venue_name_clean.include?(existing_name_clean) ||
      existing_name_clean.include?(venue_name_clean)
    end
  end

  # Filter out duplicates
  unique_venues = []
  manual_venues.each do |venue_attrs|
    if similar_venue_exists?(venue_attrs[:name], unique_venues)
      puts "Skipping duplicate venue: #{venue_attrs[:name]}"
    else
      unique_venues << venue_attrs
    end
  end

  puts "Creating #{unique_venues.length} unique venues..."

  unique_venues.each do |attrs|
    venue = Venue.create!(
      name: attrs[:name],
      street_address: attrs[:street_address],
      city: attrs[:city],
      state: attrs[:state],
      zip_code: attrs[:zip_code],
      category: attrs[:category],
      website: attrs[:website],
      latitude: attrs[:latitude],
      longitude: attrs[:longitude]
      #owner_id: owners.sample.id,
    )

    # Generate unique avatar image
    avatar_url = "https://i.pravatar.cc/300?u=#{SecureRandom.uuid}"

    venue.image.attach(
      io: URI.open(avatar_url),
      filename: "#{attrs[:name].parameterize}.png",
      content_type: "image/png",
    )

    venues << venue
  end

  30.times do
    # Generate a random start time
    random_start = Faker::Time.between(from: DateTime.now, to: DateTime.now + 2.day)

    # Round to nearest 15-minute interval
    hour = random_start.hour
    minute = (random_start.min / 15.0).round * 15

    if minute == 60
      hour += 1
      minute = 0
    end

    # Create the properly rounded start time
    start_datetime = random_start.change(hour: hour, min: minute, sec: 0)

    # Calculate end time
    durations = [1.hour, 1.5.hours, 2.hours, 2.5.hours, 3.hours, 4.hours]
    duration = durations.sample

    # For late events, make them longer to create overnight events
    if start_datetime.hour >= 22
      duration = [3.hours, 4.hours, 5.hours, 6.hours].sample
    end

    end_datetime = start_datetime + duration

    cover = [true, false].sample
    descriptions = [
      "Join us for an intimate acoustic night featuring local talent and cold drinks. Perfect for a laid-back evening with friends.",
      "Experience a soulful evening of blues and brews at your favorite neighborhood bar. Live tunes kick off right after sunset.",
      "Don't miss this high-energy cover band playing your favorite hits from the '90s to today. Great vibes, great sound.",
      "A solo singer-songwriter takes the stage with original songs and heartfelt lyrics. Grab a seat early — it's gonna fill up.",
      "Enjoy a cozy evening of jazz and cocktails in a candlelit setting. Smooth melodies, small bites, and a local crowd.",
      "A rotating lineup of local acts brings variety to the mic. Expect everything from indie rock to mellow folk sets.",
      "Come catch a one-night-only performance from a rising local artist. Genre-bending sounds and an open-air patio await.",
      "This duo blends guitar and harmonies into a perfect mix of old-school and modern covers. Drinks are half-off until 8 PM.",
      "Live music under the stars, featuring a mix of acoustic sets and upbeat originals. Bring your crew and settle in.",
      "A relaxed Sunday set with brunch vibes, acoustic instruments, and feel-good music all morning long.",
    ]
    Event.create!(
      date: start_datetime.to_date,
      start_time: start_datetime,     # Pass as datetime object
      end_time: end_datetime,         # Pass as datetime object
      description: descriptions.sample,
      cover: cover,
      cover_amount: cover ? rand(5..20) : nil,
      indoors: [true, false].sample,
      venue_id: venues.sample.id,
      artist_id: artists.sample.id,
    )
  end

  #create followed artists and venues

  User.find_each do |user|
    user_artists = artists.sample(rand(2..4)) # follow 2–4 artists
    user_venues = venues.sample(rand(2..4))  # follow 2–4 venues

    user_artists.each do |artist|
      ArtistFollow.find_or_create_by!(user: user, artist: artist)
    end

    user_venues.each do |venue|
      VenueFollow.find_or_create_by!(user: user, venue: venue)
    end
  end
end
